/**
 * The public fidelity layer, and what it does and does not prove.
 *
 * **It proves page-composition fidelity.** Given the page the archived Claude
 * Design prototype composed, the ported ESM engine lays out the same six
 * surfaces and produces the same geometry, the same line spans, the same
 * pagination and the same validator findings - compared as raw bytes against the
 * files in `fixtures/synthetic-golden/`.
 *
 * **It does not prove durable-capsule validity, and it must not be read as
 * doing so.** The composer emits a *page composition*. `capsule.schema.json`
 * describes the durable *contract*, and the two are not the same document: the
 * contract additionally requires consent, people, recordings, preservation,
 * access, version and migration - everything a family needs to reconstruct a
 * capsule without us. Assembling that is **Gate 2's**, and Stage 5 of the port
 * is explicitly partial on it. The gap is pinned below in full rather than
 * summarised, so closing it fails loudly.
 *
 * The expectations were produced by the archived prototype, loaded through plain
 * `require` - not by the code under test. An expectation generated by the thing
 * being tested proves only that it agrees with itself.
 *
 * Everything here is synthetic, so it runs on a clean public clone.
 *
 * If a comparison fails, the port is wrong. Never adjust the expectation.
 *
 * The one exception is a DECIDED departure: the prototype got something wrong,
 * the engine now does it differently on purpose, and `departures.json` says
 * which surface, which blocks, when and why. The prototype's bytes stay in
 * `expected-surfaces.json` untouched; the surface is compared against the
 * departure's own record instead, and every block the departure does not name
 * must still be the prototype's, byte for byte.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as layout from "../src/engine/layout.mjs";
import * as textlayout from "../src/engine/textlayout.mjs";
import * as engineValidate from "../src/engine/validate.mjs";
import {
  validate, checkAll, checkClosure, checkNoPixels,
  checkApprovedFragmentsOnly, checkEvidenceQuotes, checkVisualRunBindings,
} from "../src/validate/index.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(HERE, "..", "fixtures", "synthetic-golden");
const bytesOf = (name) => readFileSync(path.join(DIR, name));
const load = (name) => JSON.parse(bytesOf(name).toString("utf8"));

const input = load("input.json");
const expectedCapsule = load("expected-capsule.json");
const expectedSurfaces = load("expected-surfaces.json");
const expectedRun = load("expected-run.json");
const departures = load("departures.json");

const measure = textlayout.makeMetricMeasurer();

/**
 * The two serialisation policies in this fixture directory, both verified
 * against the files rather than assumed.
 *
 *   expected-capsule.json  - exactly how the prototype's harness wrote a page:
 *                            JSON.stringify(v, null, 2), UTF-8, NO final newline.
 *   everything else        - ordinary repository files, with a final newline.
 */
const asWriterWrote = (value) => Buffer.from(JSON.stringify(value, null, 2), "utf8");
const asRepoFile = (value) => Buffer.from(JSON.stringify(value, null, 2) + "\n", "utf8");

/** The same projection the oracle recorded, applied to a freshly composed model. */
function projection(model, report, published) {
  return {
    height: model.height,
    sizes: model.sizes,
    pagination: model.pagination ?? null,
    flow: (model.flow || []).map((f) => ({
      blockId: f.blockId, type: f.type, role: f.role, depth: f.depth,
      size: f.size, box: f.box ?? null,
      lines: (f.lines || []).map((ln) => ({ x: ln.x, y: ln.y, w: ln.w, text: ln.text,
                                            start: ln.start, end: ln.end })),
    })),
    report: {
      ok: report.ok, counts: report.counts,
      findings: (report.findings || []).map((f) => ({
        code: f.code, subject: f.subject, message: f.message, hint: f.hint })),
    },
    published,
  };
}

function composeOne(surface) {
  const capsule = JSON.parse(JSON.stringify(expectedCapsule));
  const model = layout.composeSurface({ capsule, surface, measure, fragmentsById: {} });
  const report = engineValidate.validate({
    capsule, model, approvedFragmentIds: [], scripts: expectedRun.typePalette.scripts,
  });
  return projection(model, report, report.ok);
}

// --- the fixture is stored the way the writer writes ------------------------

test("the golden page is stored in the prototype's own serialisation", () => {
  // Which is what makes every other comparison in this file a byte comparison
  // rather than a deep-equality check with the formatting thrown away.
  const raw = bytesOf("expected-capsule.json");
  assert.ok(raw.equals(asWriterWrote(expectedCapsule)),
    "expected-capsule.json is not JSON.stringify(v, null, 2) without a final newline");
  assert.equal(raw[raw.length - 1] === 0x0a, false, "the golden page has a trailing newline");
});

// --- what this layer proves --------------------------------------------------

for (const surface of input.surfaces) {
  const key = `${surface.kind}-${surface.w}`;
  test(`the ported engine reproduces the ${key} page geometry, byte for byte`, () => {
    const want = departures[key]?.expected ?? expectedSurfaces[key];
    assert.ok(want, `no recorded expectation for ${key}`);
    const got = composeOne(surface);
    const gotBytes = asRepoFile(got);
    const wantBytes = asRepoFile(want);
    assert.equal(gotBytes.length, wantBytes.length,
      `${key}: ${gotBytes.length} bytes produced, ${wantBytes.length} expected`);
    assert.ok(gotBytes.equals(wantBytes), `${key} differs`);
  });
}

test("the whole surfaces record round-trips as the file on disk", () => {
  // The per-surface tests above compare one entry each; this compares the file,
  // so a surface that quietly disappeared from the record would be caught too.
  // A departed surface is put back to the prototype's record, which is the one
  // thing a departure may not change.
  const rebuilt = {};
  for (const surface of input.surfaces) {
    const key = `${surface.kind}-${surface.w}`;
    rebuilt[key] = departures[key] ? expectedSurfaces[key] : composeOne(surface);
  }
  assert.ok(asRepoFile(rebuilt).equals(bytesOf("expected-surfaces.json")));
});

test("a departure from the prototype names every block it moved, and only those", () => {
  for (const [key, departure] of Object.entries(departures)) {
    assert.ok(expectedSurfaces[key], `${key} departs from a surface the prototype never recorded`);
    assert.match(departure.decided, /^\d{4}-\d{2}-\d{2}$/);
    assert.ok(departure.reason.length > 40, `${key}: a departure says why`);
    const was = new Map(expectedSurfaces[key].flow.map((f) => [f.blockId, JSON.stringify(f)]));
    const now = new Map(departure.expected.flow.map((f) => [f.blockId, JSON.stringify(f)]));
    assert.deepEqual([...now.keys()], [...was.keys()], `${key}: a departure may not add or drop a block`);
    const moved = [...now.keys()].filter((id) => now.get(id) !== was.get(id));
    assert.deepEqual(moved, departure.blocks, `${key}: the blocks that moved are the blocks it names`);
  }
});

test("the print sheets carry the keeps the prototype recorded", () => {
  for (const surface of input.surfaces.filter((s) => s.kind === "print")) {
    const key = `${surface.kind}-${surface.w}`;
    const pg = expectedSurfaces[key].pagination;
    assert.ok(pg, `${key} has no pagination record`);
    assert.equal(pg.keepLines, 2);
    assert.deepEqual(pg.strays, [], `${key} left a stray line`);
    assert.deepEqual(pg.oversize, [], `${key} left an oversize block`);
    assert.ok(pg.sheets.length >= 2, `${key} paginated to ${pg.sheets.length} sheet(s)`);
    assert.equal(expectedSurfaces[key].report.ok, true);
  }
});

test("composition is reproducible: composing twice gives the same bytes", () => {
  for (const surface of input.surfaces) {
    assert.ok(asRepoFile(composeOne(surface)).equals(asRepoFile(composeOne(surface))));
  }
});

// --- what this layer does NOT prove, pinned in full -------------------------

/**
 * A complete fingerprint of a validation result.
 *
 * Every field the validator exposes goes in - `path`, `keyword`, `params` and
 * `message` - because the first three are where the detail lives. Hashing only
 * path and message hid 76 of the 109 findings behind 13 identical strings: every
 * `must NOT have additional properties` reads the same and is distinguished
 * solely by its `params.additionalProperty`. A fingerprint that cannot tell
 * those apart is not a fingerprint of the failure, it is one of its wording.
 */
function fingerprint(errors) {
  const canonical = (errors ?? [])
    .map((e) => JSON.stringify({
      path: e.path,
      keyword: e.keyword,
      params: e.params === undefined ? null : sortKeys(e.params),
      message: e.message,
    }))
    .sort();
  return {
    count: canonical.length,
    sha256: createHash("sha256").update(canonical.join("\u0000"), "utf8").digest("hex"),
  };
}

/** Key order is not part of a finding, so it must not be part of its hash. */
function sortKeys(value) {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map((k) => [k, sortKeys(value[k])]));
  }
  return value;
}

const schemaResult = validate("capsule.schema.json", expectedCapsule);

test("the composed page is NOT a contract-valid capsule, and here is exactly why", () => {
  // Recorded rather than worked around, and recorded completely. An earlier
  // version pinned only the fourteen missing properties, which made the gap look
  // like a handful of absent fields. It is not: the page's block types, id
  // formats, seed format and composition shape all disagree with the contract.
  assert.equal(schemaResult.valid, false,
    "the composer now emits a contract-valid capsule - delete this test and assert validity");

  const print = fingerprint(schemaResult.errors);
  assert.equal(print.count, 109, "the number of schema findings changed");
  assert.equal(print.sha256, "3226f9347825ebbc2bd6e18a0242ad2c0ade147d809bf3f744a8394e877cc28c",
    "the schema-failure fingerprint changed; update it deliberately");

  const messages = (schemaResult.errors ?? []).map((e) => e.message);
  const missing = messages
    .filter((m) => m.startsWith("must have required property"))
    .map((m) => m.replace(/.*'(.+)'.*/, "$1")).sort();
  assert.deepEqual(missing, [
    "access", "consent", "createdAt", "editionId", "familySpaceId", "migration",
    "people", "preservation", "recordings", "schemaRevision", "sourceLocale",
    "stage", "updatedAt", "version",
  ]);

  // Not only absent fields. The page's own shapes disagree too.
  assert.ok(messages.includes('must match pattern "^cap_[0-9A-HJKMNP-TV-Z]{26}$"'),
    "the capsule id format disagreement is no longer reported");
  assert.ok(messages.includes('must match pattern "^0x[0-9a-f]{4,16}$"'),
    "the scatter-seed format disagreement is no longer reported");
  assert.ok(messages.filter((m) => m === "must be equal to one of the allowed values").length >= 11,
    "the block-type disagreements are no longer reported");
  assert.ok(messages.filter((m) => m === "must NOT have additional properties").length >= 60,
    "the extra-property disagreements are no longer reported");
});

test("the fingerprint notices a change that the message alone would hide", () => {
  // The negative control for the fingerprint itself. Mutating which property is
  // offending changes `params.additionalProperty` and nothing else - same path,
  // same keyword, same message - so a path-and-message hash would not move.
  // This one must.
  const errors = schemaResult.errors ?? [];
  const index = errors.findIndex((e) => e.keyword === "additionalProperties");
  assert.ok(index >= 0, "no additionalProperties finding to mutate");

  const mutated = errors.map((e, i) => i !== index ? e : {
    ...e,
    params: { ...e.params, additionalProperty: `${e.params.additionalProperty}_mutated` },
  });

  assert.equal(mutated[index].path, errors[index].path);
  assert.equal(mutated[index].message, errors[index].message);
  assert.equal(mutated[index].keyword, errors[index].keyword);
  assert.notEqual(fingerprint(mutated).sha256, fingerprint(errors).sha256,
    "the fingerprint ignores params, so it cannot see which property is offending");
  assert.equal(fingerprint(mutated).count, fingerprint(errors).count);

  // And key order inside params is not a change.
  const reordered = errors.map((e) => ({
    ...e,
    params: e.params && Object.fromEntries(Object.entries(e.params).reverse()),
  }));
  assert.equal(fingerprint(reordered).sha256, fingerprint(errors).sha256);
});

test("the cross-field validators that apply to a page composition are run", () => {
  // Two of the five can be run against this document and are. Two cannot, and
  // saying they passed would be a lie - see the test below. One fails, in full.
  assert.deepEqual(checkNoPixels(expectedCapsule), [],
    "no rendered pixel may appear in a capsule");
  assert.deepEqual(checkApprovedFragmentsOnly(expectedCapsule), [],
    "a voice-only page places no fragment, approved or otherwise");

  // Closure fails for the same reason the schema does: the page names recording
  // and evidence ids that only the contract capsule and its evidence map would
  // declare. Thirteen, pinned by pointer AND by identifier - the pointer says
  // where the reference is, the identifier says what is missing, and a change
  // that moved a block would otherwise slip past a pointer-only pin.
  const dangling = checkClosure(expectedCapsule, {});
  assert.equal(dangling.length, 13);
  assert.deepEqual(
    dangling.map((d) => `${d.pointer} -> ${d.id}`).sort(),
    [
      "/blocks/0/evidence/0 -> ev_synthetic_14_17",
      "/blocks/1/recordingId -> rec_synthetic",
      "/blocks/2/children/0/evidence/0 -> ev_synthetic_0_70",
      "/blocks/2/children/1/evidence/0 -> ev_synthetic_71_167",
      "/blocks/2/children/2/evidence/0 -> ev_synthetic_168_220",
      "/blocks/2/children/3/evidence/0 -> ev_synthetic_221_289",
      "/blocks/2/children/4/evidence/0 -> ev_synthetic_290_386",
      "/blocks/2/children/5/evidence/0 -> ev_synthetic_387_475",
      "/blocks/2/children/6/evidence/0 -> ev_synthetic_476_566",
      "/blocks/2/children/7/evidence/0 -> ev_synthetic_567_661",
      "/blocks/2/children/8/evidence/0 -> ev_synthetic_662_710",
      "/blocks/2/evidence/0 -> ev_synthetic_0_710",
      "/sourceRecordings/0/recordingId -> rec_synthetic",
    ],
  );

  const all = checkAll(expectedCapsule, { evidenceMap: null, fragmentManifest: null });
  assert.ok(all.length > 0, "checkAll now passes - the contract assembler landed");
  assert.equal(all.filter((f) => f.startsWith("schema ")).length, 109);
});

test("evidence-quote and visual-run validation cannot run here, and are not claimed", () => {
  // This test exists to stop the two easy lies.
  //
  // `checkEvidenceQuotes(capsule, null)` returns [] because there is no evidence
  // map to disagree with, and `checkVisualRunBindings(null)` returns [] on its
  // first line. Both are no-ops. Asserting them as passes would report coverage
  // this fixture does not have, which is worse than reporting none.
  //
  // Running them for real needs the Gate 2 contract assembly: an evidence map
  // built from the approved transcript, and an explicit empty V2 visual manifest
  // attached to an assembled capsule. Neither exists yet, by design - assembling
  // the contract is Gate 2's, not the engine's.
  //
  // The proof that they are no-ops rather than passes: a page with an obviously
  // wrong quote produces the same empty result while the map is null.
  const tampered = JSON.parse(JSON.stringify(expectedCapsule));
  tampered.blocks[0].text = "a sentence nobody in this fixture ever said";
  assert.deepEqual(checkEvidenceQuotes(tampered, null), [],
    "with a null map this check cannot catch anything, which is exactly the point");
  assert.deepEqual(checkVisualRunBindings(null), [],
    "with no manifest this check returns on its first line");
});

// --- the page itself ---------------------------------------------------------

test("the golden is what a voice-only English page actually composes to", () => {
  assert.equal(expectedRun.languagePack.detected.locale, "en");
  assert.equal(expectedRun.languagePack.detected.how, "declared");
  // The caller declared "en" and the detector agreed, but the page records
  // `und`: a locale is only claimed when a lexicon backs it, and English has
  // none. Undetermined is the honest answer.
  assert.equal(expectedCapsule.locale, "und");
  assert.equal(expectedCapsule.blocks.length, 3);
  assert.deepEqual(expectedCapsule.blocks.map((b) => b.type), ["title", "media", "ordered-list"]);
  assert.equal(expectedCapsule.blocks[2].children.length, 9,
    "the nine spoken sentences became nine items, one per sentence");
  assert.equal(expectedRun.readiness.register, "voice-only");
  assert.equal(expectedRun.readiness.counts.fragments, 0);

  // The title composes to "The" for the same reason: structuring runs on
  // lexicon.default.json, which is structure with no vocabulary. Pinned rather
  // than tidied - writing an English lexicon should visibly change this line.
  assert.equal(expectedCapsule.blocks[0].text, "The");
  assert.equal(expectedRun.languagePack.resolved.lexicon.substituted, true);
  assert.equal(expectedRun.languagePack.resolved.lexicon.locale, null);
});

test("every block's text is a span of the transcript, and carries its evidence", () => {
  // The rule the whole product rests on: nothing composed may be a sentence she
  // did not say. Case-insensitive because a title is set from a span and
  // capitalised for display - the letters are hers, the capital is presentation.
  const source = input.recording.text.toLowerCase();
  let checked = 0;
  const walk = (blocks) => {
    for (const block of blocks ?? []) {
      if (typeof block.text === "string" && block.text.length > 1) {
        checked += 1;
        assert.ok(source.includes(block.text.toLowerCase()),
          `${block.blockId} carries text that is not in the transcript: ${block.text.slice(0, 60)}`);
        assert.ok((block.evidence ?? []).length > 0,
          `${block.blockId} carries text with no evidence link`);
      }
      walk(block.children);
    }
  };
  walk(expectedCapsule.blocks);
  assert.ok(checked >= 10, `only ${checked} blocks carried text`);
});
