/**
 * The public fidelity layer: the ported engine against the prototype's output.
 *
 * `fixtures/synthetic-golden/` was produced by the ARCHIVED Claude Design
 * prototype - the Stage 1 export, loaded through plain `require`, which those
 * files support. Not by the code under test. An expectation generated by the
 * thing being tested proves only that it agrees with itself.
 *
 * What is proved here is the engine half of the port: given the capsule the
 * prototype composed, the ported ESM engine lays out the same six surfaces and
 * produces the same geometry, the same validator findings and the same
 * pagination, byte for byte. The skills half - transcript to capsule.json -
 * lives in `cookbook-agent`, because that is where the skills live and this
 * package must not depend on its own dependent.
 *
 * Everything here is synthetic. There is no family material in this repository
 * and this test does not need any: it runs on a clean public clone.
 *
 * If an assertion here fails, the port is wrong. Never adjust the expectation to
 * fit the output.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as layout from "../src/engine/layout.mjs";
import * as textlayout from "../src/engine/textlayout.mjs";
import * as engineValidate from "../src/engine/validate.mjs";
import { validate } from "../src/validate/index.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(HERE, "..", "fixtures", "synthetic-golden");
const load = (name) => JSON.parse(readFileSync(path.join(DIR, name), "utf8"));

const input = load("input.json");
const expectedCapsule = load("expected-capsule.json");
const expectedSurfaces = load("expected-surfaces.json");
const expectedRun = load("expected-run.json");

const measure = textlayout.makeMetricMeasurer();

/** The same projection the oracle recorded, applied to a freshly composed model. */
function projection(model, report, published) {
  return {
    height: model.height,
    sizes: model.sizes,
    pagination: model.pagination ?? null,
    flow: (model.flow || []).map((f) => ({
      blockId: f.blockId, type: f.type, role: f.role, depth: f.depth,
      size: f.size, box: f.box ?? null,
      lines: (f.lines || []).map((ln) => ({ x: ln.x, y: ln.y, w: ln.w, text: ln.text,
                                            start: ln.start, end: ln.end })),
    })),
    report: {
      ok: report.ok, counts: report.counts,
      findings: (report.findings || []).map((f) => ({
        code: f.code, subject: f.subject, message: f.message, hint: f.hint })),
    },
    published,
  };
}

function composeOne(surface) {
  const capsule = JSON.parse(JSON.stringify(expectedCapsule));
  const model = layout.composeSurface({
    capsule, surface, measure, fragmentsById: {},
  });
  const report = engineValidate.validate({
    capsule, model, approvedFragmentIds: [],
    scripts: expectedRun.typePalette.scripts,
  });
  return projection(model, report, report.ok);
}

// --- the capsule itself ------------------------------------------------------

test("the composed page is NOT yet a contract-valid capsule, and this pins why", () => {
  // A finding, recorded rather than worked around.
  //
  // The Claude Design composer emits a *page composition* - schemaVersion,
  // title, locale, sourceRecordings, blocks, claims, clarifications, fonts,
  // compositions, legend, provenance. `capsule.schema.json` describes the
  // durable *contract*, which additionally requires the things a family needs
  // to reconstruct a capsule without us: consent, people, recordings,
  // preservation, access, version, migration and the rest.
  //
  // Every prototype output has this gap - the four archived runs and both cold
  // starts included. It is not caused by the port, and it is not the engine's
  // to close: composing geometry is this package's job, and assembling a
  // contract-complete capsule is the cookbook agent's. Phase D owes it.
  //
  // So the gap is asserted rather than skipped. When the agent starts emitting
  // the contract shape, this test fails and is deleted, which is exactly the
  // signal that should be loud.
  const result = validate("capsule.schema.json", expectedCapsule);
  assert.equal(result.valid, false,
    "the composer now emits a contract-valid capsule - delete this test and " +
    "assert validity instead");

  const missing = (result.errors ?? [])
    .filter((e) => /must have required property/.test(e.message))
    .map((e) => e.message.replace(/.*'(.+)'.*/, "$1"))
    .sort();
  assert.deepEqual(missing, [
    "access", "consent", "createdAt", "editionId", "familySpaceId", "migration",
    "people", "preservation", "recordings", "schemaRevision", "sourceLocale",
    "stage", "updatedAt", "version",
  ], "the shape of the gap changed; update the record deliberately");
});

test("the golden is what a voice-only English capsule actually composes to", () => {
  // Pinned facts about the fixture, so a change to any of them shows up as a
  // decision rather than as drift.
  // The caller declared "en" and the detector agreed, but the composed capsule
  // records `und`: a locale is only claimed when a lexicon backs it, and English
  // has none. Undetermined is the honest answer, and pinning it here means a
  // later English lexicon has to change this line on purpose.
  assert.equal(expectedRun.languagePack.detected.locale, "en");
  assert.equal(expectedRun.languagePack.detected.how, "declared");
  assert.equal(expectedCapsule.locale, "und");
  assert.equal(expectedCapsule.blocks.length, 3);
  assert.deepEqual(expectedCapsule.blocks.map((b) => b.type), ["title", "media", "ordered-list"]);
  assert.equal(expectedCapsule.blocks[2].children.length, 9,
    "the nine spoken sentences became nine items, one per sentence");
  assert.equal(expectedRun.readiness.register, "voice-only");
  assert.equal(expectedRun.readiness.counts.fragments, 0);

  // English ships question wording and player chrome but NO lexicon, so the
  // structuring skill runs on lexicon.default.json - structure without
  // vocabulary. The title is "The" because of that, and it is pinned rather
  // than tidied: it is the prototype's own honest degrade, and writing an
  // English lexicon should visibly change this line.
  assert.equal(expectedCapsule.blocks[0].text, "The");
  assert.equal(expectedRun.languagePack.resolved.lexicon.substituted, true);
  assert.equal(expectedRun.languagePack.resolved.lexicon.locale, null);
});

test("every block's text is a span of the transcript, and carries its evidence", () => {
  // The rule the whole product rests on: nothing composed may be a sentence she
  // did not say. Comparison is case-insensitive because a title is set from a
  // span and capitalised for display - the letters are hers, the capital is
  // presentation - and every such block still has to name the span it came from.
  const source = input.recording.text.toLowerCase();
  let checked = 0;
  const walk = (blocks) => {
    for (const block of blocks ?? []) {
      if (typeof block.text === "string" && block.text.length > 1) {
        checked += 1;
        assert.ok(source.includes(block.text.toLowerCase()),
          `${block.blockId} carries text that is not in the transcript: ${block.text.slice(0, 60)}`);
        assert.ok((block.evidence ?? []).length > 0,
          `${block.blockId} carries text with no evidence link`);
      }
      walk(block.children);
    }
  };
  walk(expectedCapsule.blocks);
  assert.ok(checked >= 10, `only ${checked} blocks carried text`);
});

// --- the ported engine against the prototype's geometry ----------------------

for (const surface of input.surfaces) {
  const key = `${surface.kind}-${surface.w}`;
  test(`the ported engine reproduces ${key} byte for byte`, () => {
    const got = composeOne(surface);
    const want = expectedSurfaces[key];
    assert.ok(want, `no recorded expectation for ${key}`);
    // Byte-identical, not "close enough": a mechanical IIFE-to-ESM conversion
    // has no licence to move a coordinate.
    assert.equal(JSON.stringify(got), JSON.stringify(want));
  });
}

test("the print sheets carry the keeps and the record the prototype recorded", () => {
  for (const surface of input.surfaces.filter((s) => s.kind === "print")) {
    const key = `${surface.kind}-${surface.w}`;
    const pg = expectedSurfaces[key].pagination;
    assert.ok(pg, `${key} has no pagination record`);
    assert.equal(pg.keepLines, 2);
    assert.deepEqual(pg.strays, [], `${key} left a stray line`);
    assert.deepEqual(pg.oversize, [], `${key} left an oversize block`);
    assert.ok(pg.sheets.length >= 2, `${key} paginated to ${pg.sheets.length} sheet(s)`);
    assert.equal(expectedSurfaces[key].report.ok, true);
  }
});

test("composition is reproducible: composing twice gives the same bytes", () => {
  for (const surface of input.surfaces) {
    assert.equal(JSON.stringify(composeOne(surface)), JSON.stringify(composeOne(surface)));
  }
});
